
dist: trusty
sudo: false

language: php

php: 7.3

install:
  - composer self-update
  - composer --prefer-dist install

script:
  - ./vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 src/ tests/Test
  - ./vendor/bin/phpunit --process-isolation -v --debug --coverage-clover=coverage.clover;
  - wget https://scrutinizer-ci.com/ocular.phar;
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
